# Generated by Django 5.2.15 on 2026-07-22 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("insumos", "0001_initial"),
        ("produtos", "0003_alter_produto_options_produto_produto_peso_unico"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimentacaoInsumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada"),
                            ("SAIDA", "Saída"),
                            ("AJUSTE", "Ajuste"),
                        ],
                        max_length=10,
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                ("observacao", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "insumo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentacoes",
                        to="insumos.insumo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovimentacaoProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada"),
                            ("SAIDA", "Saída"),
                            ("AJUSTE", "Ajuste"),
                        ],
                        max_length=10,
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                ("observacao", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimentacoes",
                        to="produtos.produto",
                    ),
                ),
            ],
        ),
    ]
