# Generated by Django 5.2.15 on 2026-07-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("tipo", models.CharField(blank=True, max_length=100)),
                ("fabricante", models.CharField(blank=True, max_length=100)),
                ("numero_serie", models.CharField(blank=True, max_length=100)),
                (
                    "valor_compra",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("data_compra", models.DateField(blank=True, null=True)),
                ("garantia_meses", models.IntegerField(blank=True, null=True)),
                ("localizacao", models.CharField(blank=True, max_length=150)),
                (
                    "nota_fiscal",
                    models.FileField(blank=True, null=True, upload_to="notas_fiscais/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("manutencao", "Manutenção"),
                            ("parado", "Parado"),
                        ],
                        default="ativo",
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
            ],
        ),
    ]
