# Generated by Django 5.2.15 on 2026-07-02 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipamentos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipamento",
            options={
                "ordering": ["-id"],
                "verbose_name": "Equipamento",
                "verbose_name_plural": "Equipamentos",
            },
        ),
        migrations.RemoveField(
            model_name="equipamento",
            name="nota_fiscal",
        ),
        migrations.AddField(
            model_name="equipamento",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="equipamento",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="equipamento",
            name="garantia_meses",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="equipamento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("maquina_gelo", "Máquina de Gelo"),
                    ("freezer", "Freezer"),
                    ("bomba", "Bomba"),
                    ("compressor", "Compressor"),
                    ("outro", "Outro"),
                ],
                default="outro",
                max_length=50,
            ),
        ),
    ]
