# Generated by Django 5.2.15 on 2026-07-02 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipamentos", "0002_alter_equipamento_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoEquipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("arquivo", models.FileField(upload_to="documentos_equipamentos/")),
                ("data_upload", models.DateTimeField(auto_now_add=True)),
                (
                    "equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="equipamentos.equipamento",
                    ),
                ),
            ],
        ),
    ]
