# Generated by Django 5.2.15 on 2026-07-29 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "clientes",
            "0002_alter_cliente_options_cliente_ativo_cliente_cidade_and_more",
        ),
        ("equipamentos", "0003_documentoequipamento"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentoequipamento",
            options={
                "ordering": ["-data_upload"],
                "verbose_name": "Documento do Equipamento",
                "verbose_name_plural": "Documentos dos Equipamentos",
            },
        ),
        migrations.AddField(
            model_name="equipamento",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipamentos",
                to="clientes.cliente",
            ),
        ),
    ]
