# Generated by Django 5.0.3 on 2026-09-07 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "clientes",
            "0002_alter_cliente_options_cliente_ativo_cliente_cidade_and_more",
        ),
        ("equipamentos", "0005_medio_009_010"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContratoComodato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_contrato", models.CharField(max_length=30, unique=True)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("encerrado", "Encerrado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="ativo",
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contratos_comodato",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contratos_comodato",
                        to="equipamentos.equipamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato de comodato",
                "verbose_name_plural": "Contratos de comodato",
                "ordering": ["-data_inicio", "-id"],
            },
        ),
    ]
