# Generated by Django 5.2.15 on 2026-07-08 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="produto",
            options={},
        ),
    ]
