# Generated by Django 5.2.15 on 2026-07-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0002_alter_produto_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="produto",
            options={
                "ordering": ["peso_kg"],
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
            },
        ),
        migrations.AddConstraint(
            model_name="produto",
            constraint=models.UniqueConstraint(
                fields=("peso_kg",), name="produto_peso_unico"
            ),
        ),
    ]
