# Generated by Django 5.2.15 on 2026-08-26 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insumos", "0001_initial"),
        ("produtos", "0003_alter_produto_options_produto_produto_peso_unico"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComposicaoProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.DecimalField(decimal_places=3, default=1, max_digits=10),
                ),
                (
                    "insumo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="composicoes",
                        to="insumos.insumo",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="composicao",
                        to="produtos.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Composição do Produto",
                "verbose_name_plural": "Composições dos Produtos",
                "unique_together": {("produto", "insumo")},
            },
        ),
    ]
