# Generated by Django 5.2.15 on 2026-07-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemvenda",
            name="preco_unitario",
            field=models.DecimalField(
                blank=True, decimal_places=2, editable=False, max_digits=10, null=True
            ),
        ),
    ]
