# Generated by Django 5.0.3 on 2026-09-07 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "clientes",
            "0002_alter_cliente_options_cliente_ativo_cliente_cidade_and_more",
        ),
        ("vendas", "0002_alter_itemvenda_preco_unitario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venda",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vendas",
                to="clientes.cliente",
            ),
        ),
    ]
