# Generated by Django 5.2.15 on 2026-09-28 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0004_venda_criado_por"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Entrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endereco",
                    models.TextField(
                        help_text="Cópia do endereço usado nesta entrega. Não altera o cadastro do cliente.",
                        max_length=255,
                        verbose_name="Endereço de entrega",
                    ),
                ),
                (
                    "cidade",
                    models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("entregue", "Entregue"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "entregue_em",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Confirmada em",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entregas_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entregue_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entregas_confirmadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Confirmada por",
                    ),
                ),
                (
                    "venda",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entrega",
                        to="vendas.venda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrega",
                "verbose_name_plural": "Entregas",
                "ordering": ["criado_em", "id"],
                "permissions": [("confirmar_entrega", "Pode confirmar entrega")],
                "indexes": [
                    models.Index(
                        fields=["status", "criado_em"],
                        name="vendas_ent_status_criado_idx",
                    )
                ],
            },
        ),
    ]
