# Generated by Django 5.2.15 on 2026-09-28 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendas", "0005_entrega"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Entrega",
        ),
    ]
