# Generated by Django 5.2.15 on 2026-09-28 20:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0004_cliente_possui_equipamento_comodato_and_more"),
        ("produtos", "0004_composicaoproduto"),
        ("vendas", "0006_remover_entrega"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("aberto", "Aberto"), ("entregue", "Entregue")],
                        default="aberto",
                        max_length=20,
                    ),
                ),
                (
                    "endereco",
                    models.TextField(
                        help_text="Cópia do endereço usado neste pedido. Não altera o cadastro do cliente.",
                        max_length=255,
                        verbose_name="Endereço de entrega",
                    ),
                ),
                ("cidade", models.CharField(blank=True, max_length=100)),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "entregue_em",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedidos",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entregue_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos_entregues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venda",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pedido",
                        to="vendas.venda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "ordering": ["-criado_em", "-id"],
                "permissions": [
                    ("entregar_pedido", "Pode marcar pedido como entregue")
                ],
            },
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(
                        error_messages={
                            "invalid": "Informe a quantidade em sacos inteiros."
                        },
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="produtos.produto",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="vendas.pedido",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="pedido",
            index=models.Index(
                fields=["status", "criado_em"], name="vendas_ped_status_criado_idx"
            ),
        ),
    ]
