# Generated by Django 5.2.15 on 2026-09-12 19:19

import django.core.validators
import django.db.models.deletion
import financeiro.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0002_seed_categorias_financeiras"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContaPagar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                (
                    "competencia",
                    models.DateField(
                        help_text="Período da despesa (não confundir com o vencimento).",
                        verbose_name="Competência",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.01"),
                                message="O valor deve ser maior que zero.",
                            )
                        ],
                        verbose_name="Valor",
                    ),
                ),
                (
                    "data_emissao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de emissão"
                    ),
                ),
                (
                    "data_vencimento",
                    models.DateField(verbose_name="Data de vencimento"),
                ),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de pagamento"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("pago", "Pago"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pix", "PIX"),
                            ("boleto", "Boleto"),
                            ("ted", "TED"),
                            ("dinheiro", "Dinheiro"),
                            ("cartao", "Cartão"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Forma de pagamento",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "anexo",
                    models.FileField(
                        blank=True,
                        help_text="PDF, PNG, JPEG, DOCX ou XLSX.",
                        null=True,
                        upload_to=financeiro.models.comprovante_conta_upload_to,
                        verbose_name="Comprovante",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contas_pagar",
                        to="financeiro.categoriafinanceira",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contas_pagar_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contas_pagar",
                        to="financeiro.fornecedor",
                        verbose_name="Fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta a pagar",
                "verbose_name_plural": "Contas a pagar",
                "ordering": ["data_vencimento", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "data_vencimento"],
                        name="financeiro__status_7acc63_idx",
                    ),
                    models.Index(
                        fields=["categoria"], name="financeiro__categor_ead8b4_idx"
                    ),
                    models.Index(
                        fields=["fornecedor"], name="financeiro__fornece_1eeb93_idx"
                    ),
                    models.Index(
                        fields=["competencia"], name="financeiro__compete_cbf122_idx"
                    ),
                    models.Index(
                        fields=["data_vencimento"],
                        name="financeiro__data_ve_5ce5b9_idx",
                    ),
                ],
            },
        ),
    ]
