# Generated by Django 5.2.15 on 2026-09-12 19:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0003_contapagar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContaRecorrente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.01"),
                                message="O valor deve ser maior que zero.",
                            )
                        ],
                        verbose_name="Valor",
                    ),
                ),
                (
                    "valor_estimado",
                    models.BooleanField(
                        default=False,
                        help_text="Marque se o valor for uma estimativa e puder ser ajustado na conta gerada.",
                        verbose_name="Valor estimado",
                    ),
                ),
                (
                    "periodicidade",
                    models.CharField(
                        choices=[("mensal", "Mensal")],
                        default="mensal",
                        max_length=20,
                        verbose_name="Periodicidade",
                    ),
                ),
                (
                    "dia_vencimento",
                    models.PositiveSmallIntegerField(
                        help_text="Dia do mês (1 a 28) usado no vencimento das contas geradas.",
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="O dia de vencimento deve ser entre 1 e 28."
                            ),
                            django.core.validators.MaxValueValidator(
                                28, message="O dia de vencimento deve ser entre 1 e 28."
                            ),
                        ],
                        verbose_name="Dia de vencimento",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data inicial")),
                (
                    "data_fim",
                    models.DateField(blank=True, null=True, verbose_name="Data final"),
                ),
                ("ativa", models.BooleanField(default=True)),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contas_recorrentes",
                        to="financeiro.categoriafinanceira",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contas_recorrentes",
                        to="financeiro.fornecedor",
                        verbose_name="Fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta recorrente",
                "verbose_name_plural": "Contas recorrentes",
                "ordering": ["descricao"],
            },
        ),
        migrations.AddField(
            model_name="contapagar",
            name="recorrente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contas_geradas",
                to="financeiro.contarecorrente",
                verbose_name="Conta recorrente",
            ),
        ),
        migrations.AddConstraint(
            model_name="contapagar",
            constraint=models.UniqueConstraint(
                condition=models.Q(("recorrente__isnull", False)),
                fields=("recorrente", "competencia"),
                name="financeiro_contapagar_recorrente_competencia_unico",
            ),
        ),
    ]
