# Generated by Django 5.2.15 on 2026-09-12 20:11

import django.core.validators
import django.db.models.deletion
import financeiro.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0004_contarecorrente_contapagar_recorrente_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ObrigacaoVeiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ipva", "IPVA"),
                            ("licenciamento", "Licenciamento"),
                            ("seguro", "Seguro"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("exercicio", models.PositiveIntegerField(verbose_name="Exercício")),
                (
                    "data_vencimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de vencimento"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("pago", "Pago"),
                            ("isento", "Isento"),
                            ("nao_aplicavel", "Não aplicável"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "valor_previsto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Valor previsto",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Obrigação de veículo",
                "verbose_name_plural": "Obrigações de veículos",
                "ordering": ["-exercicio", "tipo", "veiculo"],
            },
        ),
        migrations.CreateModel(
            name="PlanoManutencao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120, verbose_name="Nome")),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "intervalo_km",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Intervalo (km)",
                    ),
                ),
                (
                    "intervalo_meses",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Intervalo (meses)",
                    ),
                ),
                (
                    "antecedencia_alerta_km",
                    models.PositiveIntegerField(
                        default=1000, verbose_name="Alerta antecipado (km)"
                    ),
                ),
                (
                    "antecedencia_alerta_dias",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Alerta antecipado (dias)"
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Plano de manutenção",
                "verbose_name_plural": "Planos de manutenção",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(max_length=80, verbose_name="Marca")),
                ("modelo", models.CharField(max_length=80, verbose_name="Modelo")),
                (
                    "versao",
                    models.CharField(blank=True, max_length=80, verbose_name="Versão"),
                ),
                (
                    "placa",
                    models.CharField(max_length=8, unique=True, verbose_name="Placa"),
                ),
                (
                    "renavam",
                    models.CharField(blank=True, max_length=11, verbose_name="RENAVAM"),
                ),
                (
                    "ano_fabricacao",
                    models.PositiveIntegerField(verbose_name="Ano de fabricação"),
                ),
                ("ano_modelo", models.PositiveIntegerField(verbose_name="Ano modelo")),
                (
                    "uf",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        default="SP",
                        max_length=2,
                        verbose_name="UF",
                    ),
                ),
                (
                    "km_atual",
                    models.PositiveIntegerField(default=0, verbose_name="Km atual"),
                ),
                (
                    "data_aquisicao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de aquisição"
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Veículo",
                "verbose_name_plural": "Veículos",
                "ordering": ["marca", "modelo", "placa"],
            },
        ),
        migrations.CreateModel(
            name="ManutencaoVeiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_realizacao",
                    models.DateField(verbose_name="Data de realização"),
                ),
                (
                    "km_realizacao",
                    models.PositiveIntegerField(verbose_name="Km da realização"),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "anexo",
                    models.FileField(
                        blank=True,
                        help_text="PDF, PNG, JPEG, DOCX ou XLSX.",
                        null=True,
                        upload_to=financeiro.models.anexo_manutencao_upload_to,
                        verbose_name="Anexo",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manutencoes_veiculo_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manutencoes_veiculo",
                        to="financeiro.fornecedor",
                        verbose_name="Fornecedor",
                    ),
                ),
                (
                    "plano",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historico",
                        to="financeiro.planomanutencao",
                        verbose_name="Plano",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manutencoes",
                        to="financeiro.veiculo",
                        verbose_name="Veículo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manutenção de veículo",
                "verbose_name_plural": "Manutenções de veículos",
                "ordering": ["-data_realizacao", "-km_realizacao", "-id"],
            },
        ),
        migrations.AddField(
            model_name="contapagar",
            name="manutencao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contas_pagar",
                to="financeiro.manutencaoveiculo",
                verbose_name="Manutenção",
            ),
        ),
        migrations.AddField(
            model_name="contapagar",
            name="obrigacao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contas_pagar",
                to="financeiro.obrigacaoveiculo",
                verbose_name="Obrigação do veículo",
            ),
        ),
        migrations.AddField(
            model_name="planomanutencao",
            name="veiculo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="planos",
                to="financeiro.veiculo",
                verbose_name="Veículo",
            ),
        ),
        migrations.AddField(
            model_name="obrigacaoveiculo",
            name="veiculo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="obrigacoes",
                to="financeiro.veiculo",
                verbose_name="Veículo",
            ),
        ),
        migrations.AddField(
            model_name="contapagar",
            name="veiculo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contas_pagar",
                to="financeiro.veiculo",
                verbose_name="Veículo",
            ),
        ),
        migrations.AddIndex(
            model_name="contapagar",
            index=models.Index(
                fields=["veiculo"], name="financeiro__veiculo_60df42_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="obrigacaoveiculo",
            constraint=models.UniqueConstraint(
                fields=("veiculo", "tipo", "exercicio"),
                name="financeiro_obrigacao_veiculo_tipo_exercicio_unico",
            ),
        ),
    ]
