# Generated by Django 5.2.15 on 2026-09-13 00:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0006_categorias_veiculos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriafinanceira",
            name="exige_veiculo",
            field=models.BooleanField(
                default=False,
                help_text="Se marcado, a ContaPagar desta categoria exige a seleção de um veículo.",
            ),
        ),
        migrations.AddIndex(
            model_name="contapagar",
            index=models.Index(
                fields=["status", "data_pagamento"],
                name="financeiro_cp_status_pagto_idx",
            ),
        ),
    ]
