# Generated by Django 5.2.15 on 2026-09-13 02:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0004_cliente_possui_equipamento_comodato_and_more"),
        ("financeiro", "0007_contapagar_status_pagamento_idx"),
        ("vendas", "0004_venda_criado_por"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContaReceber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                (
                    "competencia",
                    models.DateField(
                        help_text="Período da receita (não confundir com o vencimento).",
                        verbose_name="Competência",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.01"),
                                message="O valor deve ser maior que zero.",
                            )
                        ],
                        verbose_name="Valor",
                    ),
                ),
                (
                    "data_emissao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de emissão"
                    ),
                ),
                (
                    "data_vencimento",
                    models.DateField(verbose_name="Data de vencimento"),
                ),
                (
                    "data_recebimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de recebimento"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("recebida", "Recebida"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "forma_recebimento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pix", "PIX"),
                            ("dinheiro", "Dinheiro"),
                            ("cartao_credito", "Cartão de crédito"),
                            ("cartao_debito", "Cartão de débito"),
                            ("transferencia", "Transferência"),
                            ("boleto", "Boleto"),
                            ("cheque", "Cheque"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Forma de recebimento",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contas_receber",
                        to="financeiro.categoriafinanceira",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contas_receber",
                        to="clientes.cliente",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contas_receber_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venda",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conta_receber",
                        to="vendas.venda",
                        verbose_name="Venda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta a receber",
                "verbose_name_plural": "Contas a receber",
                "ordering": ["data_vencimento", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "data_vencimento"],
                        name="financeiro__status_f45da9_idx",
                    ),
                    models.Index(
                        fields=["categoria"], name="financeiro__categor_23dca0_idx"
                    ),
                    models.Index(
                        fields=["cliente"], name="financeiro__cliente_3de520_idx"
                    ),
                    models.Index(
                        fields=["competencia"], name="financeiro__compete_ed4151_idx"
                    ),
                    models.Index(
                        fields=["data_vencimento"],
                        name="financeiro__data_ve_9e57f0_idx",
                    ),
                ],
            },
        ),
    ]
