from django.urls import path

from .views import (
    AlternarAtivoCategoriaView,
    AlternarAtivoContaRecorrenteView,
    AlternarAtivoFornecedorView,
    CancelarContaPagarView,
    CriarCategoriaView,
    CriarContaPagarView,
    CriarContaRecorrenteView,
    CriarFornecedorView,
    DashboardFinanceiroView,
    DownloadAnexoContaPagarView,
    EditarCategoriaView,
    EditarContaPagarView,
    EditarContaRecorrenteView,
    EditarFornecedorView,
    GerarContasRecorrentesView,
    ListaCategoriasView,
    ListaContasPagarView,
    ListaContasRecorrentesView,
    ListaFornecedoresView,
    MarcarContaPagaView,
    RelatoriosFinanceiroView,
)
from .views_receber import (
    CancelarContaReceberView,
    CriarContaReceberView,
    EditarContaReceberView,
    ListaContasReceberView,
    MarcarContaRecebidaView,
)
from .views_veiculos import (
    AlternarAtivoPlanoView,
    AlternarAtivoVeiculoView,
    CriarManutencaoVeiculoView,
    CriarPlanoVeiculoView,
    CriarVeiculoView,
    DetalheManutencaoVeiculoView,
    DetalheObrigacaoView,
    DetalheVeiculoView,
    DownloadAnexoManutencaoView,
    EditarManutencaoVeiculoView,
    EditarObrigacaoView,
    EditarPlanoVeiculoView,
    EditarVeiculoView,
    GerarObrigacoesView,
    ListaManutencoesVeiculoView,
    ListaObrigacoesView,
    ListaPlanosVeiculoView,
    ListaVeiculosView,
)

app_name = "financeiro"

urlpatterns = [
    path("", DashboardFinanceiroView.as_view(), name="dashboard"),
    path("relatorios/", RelatoriosFinanceiroView.as_view(), name="relatorios"),
    path("contas-pagar/", ListaContasPagarView.as_view(), name="lista_contas_pagar"),
    path(
        "contas-pagar/cadastrar/",
        CriarContaPagarView.as_view(),
        name="cadastrar_conta_pagar",
    ),
    path(
        "contas-pagar/<int:pk>/editar/",
        EditarContaPagarView.as_view(),
        name="editar_conta_pagar",
    ),
    path(
        "contas-pagar/<int:pk>/marcar-paga/",
        MarcarContaPagaView.as_view(),
        name="marcar_conta_paga",
    ),
    path(
        "contas-pagar/<int:pk>/cancelar/",
        CancelarContaPagarView.as_view(),
        name="cancelar_conta_pagar",
    ),
    path(
        "contas-pagar/<int:pk>/anexo/",
        DownloadAnexoContaPagarView.as_view(),
        name="download_anexo_conta_pagar",
    ),
    path("contas-receber/", ListaContasReceberView.as_view(), name="lista_contas_receber"),
    path(
        "contas-receber/cadastrar/",
        CriarContaReceberView.as_view(),
        name="cadastrar_conta_receber",
    ),
    path(
        "contas-receber/<int:pk>/editar/",
        EditarContaReceberView.as_view(),
        name="editar_conta_receber",
    ),
    path(
        "contas-receber/<int:pk>/marcar-recebida/",
        MarcarContaRecebidaView.as_view(),
        name="marcar_conta_recebida",
    ),
    path(
        "contas-receber/<int:pk>/cancelar/",
        CancelarContaReceberView.as_view(),
        name="cancelar_conta_receber",
    ),
    path(
        "contas-recorrentes/",
        ListaContasRecorrentesView.as_view(),
        name="lista_contas_recorrentes",
    ),
    path(
        "contas-recorrentes/cadastrar/",
        CriarContaRecorrenteView.as_view(),
        name="cadastrar_conta_recorrente",
    ),
    path(
        "contas-recorrentes/gerar/",
        GerarContasRecorrentesView.as_view(),
        name="gerar_contas_recorrentes",
    ),
    path(
        "contas-recorrentes/<int:pk>/editar/",
        EditarContaRecorrenteView.as_view(),
        name="editar_conta_recorrente",
    ),
    path(
        "contas-recorrentes/<int:pk>/alternar-ativo/",
        AlternarAtivoContaRecorrenteView.as_view(),
        name="alternar_ativo_conta_recorrente",
    ),
    path("fornecedores/", ListaFornecedoresView.as_view(), name="lista_fornecedores"),
    path(
        "fornecedores/cadastrar/",
        CriarFornecedorView.as_view(),
        name="cadastrar_fornecedor",
    ),
    path(
        "fornecedores/<int:pk>/editar/",
        EditarFornecedorView.as_view(),
        name="editar_fornecedor",
    ),
    path(
        "fornecedores/<int:pk>/alternar-ativo/",
        AlternarAtivoFornecedorView.as_view(),
        name="alternar_ativo_fornecedor",
    ),
    path("categorias/", ListaCategoriasView.as_view(), name="lista_categorias"),
    path(
        "categorias/cadastrar/",
        CriarCategoriaView.as_view(),
        name="cadastrar_categoria",
    ),
    path(
        "categorias/<int:pk>/editar/",
        EditarCategoriaView.as_view(),
        name="editar_categoria",
    ),
    path(
        "categorias/<int:pk>/alternar-ativo/",
        AlternarAtivoCategoriaView.as_view(),
        name="alternar_ativo_categoria",
    ),
    path("veiculos/", ListaVeiculosView.as_view(), name="lista_veiculos"),
    path("veiculos/cadastrar/", CriarVeiculoView.as_view(), name="cadastrar_veiculo"),
    path(
        "veiculos/obrigacoes/",
        ListaObrigacoesView.as_view(),
        name="lista_obrigacoes",
    ),
    path(
        "veiculos/obrigacoes/gerar/",
        GerarObrigacoesView.as_view(),
        name="gerar_obrigacoes",
    ),
    path(
        "veiculos/obrigacoes/<int:pk>/",
        DetalheObrigacaoView.as_view(),
        name="detalhe_obrigacao",
    ),
    path(
        "veiculos/obrigacoes/<int:pk>/editar/",
        EditarObrigacaoView.as_view(),
        name="editar_obrigacao",
    ),
    path("veiculos/<int:pk>/", DetalheVeiculoView.as_view(), name="detalhe_veiculo"),
    path(
        "veiculos/<int:pk>/editar/",
        EditarVeiculoView.as_view(),
        name="editar_veiculo",
    ),
    path(
        "veiculos/<int:pk>/alternar-ativo/",
        AlternarAtivoVeiculoView.as_view(),
        name="alternar_ativo_veiculo",
    ),
    path(
        "veiculos/<int:pk>/planos/",
        ListaPlanosVeiculoView.as_view(),
        name="lista_planos_veiculo",
    ),
    path(
        "veiculos/<int:pk>/planos/cadastrar/",
        CriarPlanoVeiculoView.as_view(),
        name="cadastrar_plano_veiculo",
    ),
    path(
        "veiculos/<int:pk>/planos/<int:plano_pk>/editar/",
        EditarPlanoVeiculoView.as_view(),
        name="editar_plano_veiculo",
    ),
    path(
        "veiculos/<int:pk>/planos/<int:plano_pk>/alternar-ativo/",
        AlternarAtivoPlanoView.as_view(),
        name="alternar_ativo_plano",
    ),
    path(
        "veiculos/<int:pk>/manutencoes/",
        ListaManutencoesVeiculoView.as_view(),
        name="lista_manutencoes",
    ),
    path(
        "veiculos/<int:pk>/manutencoes/cadastrar/",
        CriarManutencaoVeiculoView.as_view(),
        name="cadastrar_manutencao",
    ),
    path(
        "veiculos/<int:pk>/manutencoes/<int:manutencao_pk>/",
        DetalheManutencaoVeiculoView.as_view(),
        name="detalhe_manutencao",
    ),
    path(
        "veiculos/<int:pk>/manutencoes/<int:manutencao_pk>/editar/",
        EditarManutencaoVeiculoView.as_view(),
        name="editar_manutencao",
    ),
    path(
        "veiculos/<int:pk>/manutencoes/<int:manutencao_pk>/anexo/",
        DownloadAnexoManutencaoView.as_view(),
        name="download_anexo_manutencao",
    ),
]
