# Generated by Django 5.2.15 on 2026-07-08 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipamentos", "0003_documentoequipamento"),
        ("produtos", "0002_alter_produto_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Producao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                ("observacao", models.TextField(blank=True)),
                (
                    "equipamento",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "maquina_gelo"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="equipamentos.equipamento",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="produtos.produto",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_hora"],
            },
        ),
    ]
