# Generated by Django 5.2.15 on 2026-07-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cliente",
            options={},
        ),
        migrations.AddField(
            model_name="cliente",
            name="ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="cidade",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="cliente",
            name="cnpj",
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="cliente",
            name="observacoes",
            field=models.TextField(blank=True),
        ),
    ]
