# Generated by Django 5.2.15 on 2026-09-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "clientes",
            "0002_alter_cliente_options_cliente_ativo_cliente_cidade_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="endereco",
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
