# Generated by Django 5.2.15 on 2026-09-12

from django.db import migrations, models


def normalizar_cnpjs_e_preencher_comodato(apps, schema_editor):
    Cliente = apps.get_model("clientes", "Cliente")
    Equipamento = apps.get_model("equipamentos", "Equipamento")
    ContratoComodato = apps.get_model("equipamentos", "ContratoComodato")

    for cliente in Cliente.objects.exclude(cnpj__isnull=True).exclude(cnpj=""):
        digitos = "".join(caractere for caractere in cliente.cnpj if caractere.isdigit())
        novo = digitos or None
        if novo != cliente.cnpj:
            cliente.cnpj = novo
            cliente.save(update_fields=["cnpj"])

    ids_com_equipamento = Equipamento.objects.exclude(cliente_id=None).values_list(
        "cliente_id",
        flat=True,
    )
    ids_com_contrato = ContratoComodato.objects.values_list("cliente_id", flat=True)
    Cliente.objects.filter(
        models.Q(id__in=ids_com_equipamento) | models.Q(id__in=ids_com_contrato)
    ).update(possui_equipamento_comodato=True)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0003_alter_cliente_endereco"),
        ("equipamentos", "0006_contrato_comodato"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cliente",
            options={
                "ordering": ["nome"],
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.AddField(
            model_name="cliente",
            name="possui_equipamento_comodato",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Declaração operacional: o cliente opera com equipamento em "
                    "comodato, mesmo antes de um equipamento ou contrato específico "
                    "estar vinculado."
                ),
                verbose_name="Possui equipamento em comodato",
            ),
        ),
        migrations.RunPython(
            normalizar_cnpjs_e_preencher_comodato,
            noop_reverse,
        ),
    ]
